### ISSUE TITLE
Trouble loading some FITS files

### ISSUE THREAD

**Issue by aferrero2707** [jcupitt/libvips#584]
I am trying to use VIPS to load some FITS files, but I somehow cannot manage.

Here is a minimal example of failing code: https://gist.github.com/aferrero2707/43757a6c85a2523618182414e68b3101

An example of FITS file that cannot be loaded is here: https://filebin.net/52ipk309a9t90di2

Here is the output of my test program with this specific file:

    image:            0x7fa19188b010
    # of bands:       1
    band format:      3
    type:             1
    image dimensions: 4656 x 3520
    saving test buffer (image=0x7fa19188b010)...
    test buffer saved (mem_array=0x0, array_sz=0).
    memory: high-water mark 36.94 MB
    error buffer: fits: datatype conversion overflow

GIMP can load this file correctly, so I tend to exclude a problem with the file itself. Also, my code is able to properly load other sample FITS files from NASA.

Is there something I am overlooking, or is this a limitation/bug of the VIPS FITS loader?

Thanks!

**Comment by jcupitt** [comment]
Hi Andrea, this was fixed a week or so ago: images which used bzero or bscale (fits lets you attach metadata saying how pixels should be offset and scaled for display, and cfitsio insists on interpreting them for you) failed to load.

Your test image seems to work with git master.

**Comment by aferrero2707** [comment]
Great! Thanks for the info, I will test with git master as soon as I manage.

**Comment by aferrero2707** [comment]
I confirm that with git master I can load the FITS file mentioned in the first post. However, there are other FITS files that still do not load, an example of which can be found in the newtwork folder: https://mega.nz/#F!hNIkSaYZ!JhrjpaUCUsAea0TqSBxLBQ

All files named ```2017-01-15_m42-Ha_Stack*.FTS``` file with an error message of the type 

    is not a known file format

Please note that GIMP successfully loads those files, so I tend to exclude some sort of corruption...

**Comment by jcupitt** [comment]
Good news about git master.

I'll try one of those others.

**Comment by jcupitt** [comment]
I think it's just the suffix. I see:

```
$ vipsheader 2017-01-15_m42-Ha_Stack\(kappa2\ 5i\)16i.FTS 
2017-01-15_m42-Ha_Stack(kappa2 5i)16i.FTS: 4656x3520 ushort, 1 band, grey16, magickload
```

ie. it's using the ImageMagick loader. If I rename it:

```
$ cp 2017-01-15_m42-Ha_Stack\(kappa2\ 5i\)16i.FTS x.fits
$ vipsheader x.fits 
x.fits: 4656x3520 ushort, 1 band, grey16, fitsload
```

and it loads into nip2 correctly. The fits loader does try to use the .FTS suffix, I wonder why it didn't use `fitsload`? I'll have a look.

**Comment by jcupitt** [comment]
Oh, it's the paranthesis, I think. If I do:

```
$ cp 2017-01-15_m42-Ha_Stack\(kappa2\ 5i\)16i.FTS x.FTS
$ vipsheader x.FTS
```

it works. If I trace down, it's cfitsio that's triggering the error:

```
vips_foreign_find_load_sub: fitsload
isfits: testing "2017-01-15_m42-Ha_Stack(kappa2 5i)16i.FTS"
isfits: error reading "2017-01-15_m42-Ha_Stack(kappa2 5i)16i.FTS"
isfits: fits: could not open the named file
```

That's a call to `fits_open_image()` failing on that filename. I guess parenthesis have some special meaning to cfitsio. I'll try looking in there.

**Comment by aferrero2707** [comment]
Ah! I tried to change the suffix to .fits, but I haven't thought about the parenthesis... thanks! and sorry for the noise...

If there is no solution for the parenthesis, I think it is not a big deal, one just needs to know that.

**Comment by jcupitt** [comment]
libvips was using fits_open_file(), which parses extended filename formats. I've swapped it to use fits_open_diskfile(), which just opens the literal filename. It seems to work now!

**Comment by jcupitt** [comment]
I think this is done, I'll close.
